const PDFDocument = require('pdfkit');
const fs = require('fs');
const path = require('path');

/**
 * PDF SERVICE
 * 
 * Creates PDF files from markdown notes
 * PDFs are saved in the /pdfs folder
 */

// Directory where PDFs are saved
const PDF_DIR = path.join(__dirname, '../../pdfs');

// Create pdfs directory if it doesn't exist
if (!fs.existsSync(PDF_DIR)) {
  fs.mkdirSync(PDF_DIR, { recursive: true });
}

/**
 * Generate a PDF from markdown notes
 * 
 * @param {string} lessonTitle - Title of the lesson
 * @param {string} notesMarkdown - Notes in markdown format
 * @param {string} courseTitle - Title of the course (for header)
 * @param {number} lessonOrder - Lesson number (1, 2, 3...)
 * @returns {Promise<Object>} - {filename, filepath, url}
 */
const generatePDF = (lessonTitle, notesMarkdown, courseTitle, lessonOrder) => {
  return new Promise((resolve, reject) => {
    try {
      // ── Step 1: Generate unique filename ──────────────────────────────────────
      const timestamp = Date.now();
      const safeName = lessonTitle.replace(/[^a-z0-9]/gi, '_').toLowerCase();
      const filename = `notes_${safeName}_${timestamp}.pdf`;
      const filepath = path.join(PDF_DIR, filename);

      // ── Step 2: Create PDF document ───────────────────────────────────────────
      const pdfDocument = new PDFDocument({
        margins: { top: 50, bottom: 50, left: 50, right: 50 }
      });

      // ── Step 3: Create write stream ───────────────────────────────────────────
      // This saves the PDF to a file as we create it
      const writeStream = fs.createWriteStream(filepath);
      pdfDocument.pipe(writeStream);

      // ── Step 4: Add header ────────────────────────────────────────────────────
      pdfDocument.fontSize(20).font('Helvetica-Bold').text(courseTitle, { align: 'center' });
      pdfDocument.moveDown(0.5);
      pdfDocument.fontSize(16).font('Helvetica').text(`Lesson ${lessonOrder}: ${lessonTitle}`, { align: 'center' });
      pdfDocument.moveDown(1);
      
      // Divider line
      pdfDocument.moveTo(50, pdfDocument.y).lineTo(550, pdfDocument.y).stroke();
      pdfDocument.moveDown(1);

      // ── Step 5: Parse markdown and add content ────────────────────────────────
      const lines = notesMarkdown.split('\n');
      
      for (const line of lines) {
        // Headers
        if (line.startsWith('# ')) {
          pdfDocument.fontSize(18).font('Helvetica-Bold').text(line.slice(2));
          pdfDocument.moveDown(0.5);
        } 
        else if (line.startsWith('## ')) {
          pdfDocument.fontSize(14).font('Helvetica-Bold').text(line.slice(3));
          pdfDocument.moveDown(0.3);
        } 
        else if (line.startsWith('### ')) {
          pdfDocument.fontSize(12).font('Helvetica-Bold').text(line.slice(4));
          pdfDocument.moveDown(0.3);
        }
        // Bullet points
        else if (line.startsWith('- ') || line.startsWith('* ')) {
          pdfDocument.fontSize(11).font('Helvetica').text('• ' + line.slice(2), { indent: 20 });
        }
        // Normal text
        else if (line.trim() !== '') {
          pdfDocument.fontSize(11).font('Helvetica').text(line);
        }
        
        if (line.trim() !== '') {
          pdfDocument.moveDown(0.3);
        }
      }

      // ── Step 6: Add footer ────────────────────────────────────────────────────
      pdfDocument.fontSize(8).font('Helvetica').text(
        `Generated by AI Learning Platform • ${new Date().toLocaleDateString()}`,
        50,
        pdfDocument.page.height - 50,
        { align: 'center' }
      );

      // ── Step 7: Finalize PDF ──────────────────────────────────────────────────
      pdfDocument.end();

      // ── Step 8: Return result when done ───────────────────────────────────────
      writeStream.on('finish', () => {
        resolve({
          filename: filename,
          filepath: filepath,
          url: `/api/courses/notes/pdf/${filename}`
        });
      });

      writeStream.on('error', reject);

    } catch (error) {
      reject(error);
    }
  });
};

module.exports = { generatePDF };